### ISSUE TITLE
Refactoring: Migration of visual regression tests and testfile restructering

### ISSUE THREAD

**Issue by jeripeierSBB** [sbb-design-systems/lyne-components#2731]
For every component we would like to:

- Check if tests are in the appropriate file (should be done already)
- Snapshot tests
  - Should avoid using inline snapshots where possible
  - Should wrap the test with describe('Test name') and contain it('DOM', ...) and it('Shadow DOM') like
```
  describe('renders', () => {
    beforeEach(async () => {
      element = await fixture(html`<sbb-card></sbb-card>`);
    });

    it('DOM', async () => {
      await expect(element).dom.to.be.equalSnapshot();
    });

    it('Shadow DOM', async () => {
      await expect(element).shadowDom.to.be.equalSnapshot();
    });

    testA11yTreeSnapshot();
  });
```
- Adapt all Chromatic tests to the new visual tests using the utility functions. Keep the Chromatic tests during migration (We could clean up Chromatic specific stories when the new tests successfully elaborated and everything is migrated.)
  - Try to avoid unnecessary screenshots
    - As a base rule, every viewport should be included. However we have a lot of components where e.g. only viewport sizes make sense to tests (e.g. button)
    - Only test states that makes sense (e.g. no active state if there is non implemented...)

## Helpful Commands
- Run all tests: `FORCE_LOCAL=true yarn test:visual-regression --watch` (start tests on local machine (not Container))
- Run specific file: `yarn test:visual-regression --file=$FileDirRelativeToProjectRoot$/$FileName$`
- `start:visual-regression-app` (has to be restarted after every run)

## Component list

- [x] elements-experimental/journey-summary @DavideMininni-Fincons #2920
- [x] elements-experimental/pearl-chain @TomMenga #2911
- [x] elements-experimental/pearl-chain-time @TomMenga #2913
- [x] elements-experimental/pearl-chain-vertical @DavideMininni-Fincons  #2915
- [x] elements-experimental/pearl-chain-vertical-item @DavideMininni-Fincons  #2915
- [x] elements-experimental/teaser-hero @TomMenga #2914
- [x] elements-experimental/teaser-paid @TomMenga #2914
- [x] elements-experimental/timetable-duration @TomMenga #2916
- [x] elements-experimental/timetable-row @TomMenga #2916
- [x] elements/accordion - @TomMenga 
- [x] elements/action-group - @DavideMininni-Fincons #2750 
- [x] elements/alert - @dauriamarco @jeripeierSBB 
- [x] elements/autocomplete - @DavideMininni-Fincons within #2512
- [x] elements/autocomplete-grid - @DavideMininni-Fincons within #2512
- [x] elements/breadcrumb - @DavideMininni-Fincons #2752 
- [x] elements/button @jeripeierSBB 
- [x] elements/calendar @DavideMininni-Fincons #2789 
- [x] elements/card @TomMenga 
- [x] elements/checkbox @DavideMininni-Fincons #2859 
- [x] elements/chip @TomMenga #2794 
- [x] elements/clock @TomMenga #2795 
- [x] elements/container @TomMenga #2798 
- [x] elements/datepicker @DavideMininni-Fincons #2797 
- [x] elements/dialog @TomMenga #2813 
- [x] elements/divider @TomMenga #2800
- [x] elements/expansion-panel @TomMenga 
- [x] elements/file-selector @DavideMininni-Fincons #2812 
- [x] elements/footer @TomMenga #2818 
- [x] elements/form-error @DavideMininni-Fincons #2807 
- [x] elements/form-field @DavideMininni-Fincons #2807 
- [x] elements/header @DavideMininni-Fincons #2820
- [x] elements/icon @DavideMininni-Fincons #2826
- [x] elements/image @jeripeierSBB 
- [x] elements/journey-header @TomMenga #2837 
- [x] elements/lead-container @jeripeierSBB 
- [x] elements/link @DavideMininni-Fincons #2844 
- [x] elements/link-list @TomMenga #2839
- [x] elements/loading-indicator @TomMenga  #2841 
- [x] elements/logo @TomMenga #2846 
- [x] elements/map-container @TomMenga #2847 
- [x] elements/menu @DavideMininni-Fincons #2852 
- [x] elements/message - @dauriamarco 
- [x] elements/navigation @TomMenga #2863 
- [x] elements/notification @DavideMininni-Fincons #2855 
- [x] elements/option - @DavideMininni-Fincons within #2512
- [x] elements/overlay @DavideMininni-Fincons #2864 
- [x] elements/popover @TomMenga #2882
- [x] elements/radio-button @MarioCastigliano #2908
- [x] elements/screen-reader-only @DavideMininni-Fincons #2868 
- [x] elements/select @DavideMininni-Fincons #2878 
- [x] elements/selection-expansion-panel @TomMenga #2895
- [x] elements/signet @jeripeierSBB 
- [x] elements/skiplink-list @TomMenga #2888 
- [x] elements/slider @DavideMininni-Fincons #2896 
- [x] elements/status @jeripeierSBB 
- [x] elements/stepper @TomMenga #2901
- [x] elements/table-wrapper @TomMenga #2715 
- [x] elements/tabs @MarioCastigliano #2867 
- [x] elements/tag @DavideMininni-Fincons #2898
- [x] elements/teaser @DavideMininni-Fincons #2899 
- [x] elements/time-input @TomMenga #2903
- [x] elements/timetable-occupancy @TomMenga #2918
- [x] elements/timetable-occupancy-icon @jeripeierSBB 
- [x] elements/title @MarioCastigliano #2869 
- [x] elements/toast @TomMenga #2883 
- [x] elements/toggle @MarioCastigliano #2827 
- [x] elements/toggle-check @MarioCastigliano #2827 
- [x] elements/train @jeripeierSBB 
- [x] elements/visual-checkbox @jeripeierSBB 
- [x] storybook/styles @jeripeierSBB 

----
- [x] Add `compoent.visual.spec.ts` boilerplate @DavideMininni-Fincons #2910

**Comment by TomMenga** [comment]
Components with missing visual spec (checked if intentional):
- [x] timetable-occupancy (soon to be merged)
- [x] tab
- [x] step
- [x] navigation-marker
- [x] navigation-list
- [x] expansion-panel-header
- [x] expansion-panel-content
- [x] dialog-title
- [x] dialog-content
- [x] dialog-actions
- [x] card-badge
- [ ] transparent-button-static
- [ ] transparent-button-link
- [ ] tertiary-button-static
- [ ] tertiary-button-link
- [ ] secondary-button-static
- [ ] secondary-button-link
